spring.datasource.url=jdbc:postgresql://localhost:5432/devconnect_db
spring.datasource.username=postgres
spring.datasource.password=ArpitA@12

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true